### ISSUE TITLE
Syntacks error

### ISSUE THREAD

**Issue by helmutschneider** [JacobNorlin/adventofcode2021#3]
I try running in console but receive strange error

```shell
[23:50:36] johan:~/Desktop/jacob/adventofcode2021/src $ node main.rs
/Users/johan/Desktop/jacob/adventofcode2021/src/main.rs:1
pub mod day1;
    ^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by JacobNorlin** [comment]
I have added js capabilites to my project.
Please try running `node main.js` in the root folder.

**Comment by helmutschneider** [comment]
Ok works!!! genius big brain solution thank you sir
